### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by aivus** [Madlexx/symfonyApplication#18]
Please, check entities config:
```
    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            inversedBy: post
```

I can't find field `post` in User. What is it?

Also, please, use full name of entities.
`Application\BlogBundle\Entity\Category` not a `Category`
